### ISSUE TITLE
Speedup opportunity for the 8-bit font

### ISSUE THREAD

**Issue by nagydani** [cheveron/sebasic4#44]
Instead of storing the rows of a character next to one another, it is worth storing them 256 bytes apart. Essentially, you draw the font from the top left corner left to right on an Altwasser screen and save the top third. It's the same 2 kilobytes as the current format but does not require shifting the character code; it simply becomes the LSB of the address. The speedup is quite substantial. Enterprise stores its 8-bit font this way.

**Comment by cheveron** [comment]
Definitely worthy of consideration. It would make a big difference to performance on legacy hardware. A tool to convert from the current format would be required though, because that's what the standard editors use. It might make POKEing character values a bit less intuitive though:

```
POKE USR "A", %00111000
POKE USR "A"+256, %01101100
POKE USR "A"+512, %01101100
POKE USR "A"+768, %01111100
POKE USR "A"+1024, %01101100
POKE USR "A"+1280, %01101100
POKE USR "A"+1536, %01101100
POKE USR "A"+1792, %00000000
```

**Comment by cheveron** [comment]
Delay until the final release of this version (4.2.9).

**Comment by cheveron** [comment]
Closed for now. Reopen for final 4.29 release.
