### ISSUE TITLE
README.MD not complete

### ISSUE THREAD

**Issue by bodhi-baum** [cheveron/sebasic4#58]
In the subsection Linux it says:

### Linux

* Install _Wine_: `sudo apt-get install wine`
* Build the emulator: https://github.com/chernandezba/zesarux
* Modify the `task.json` file in the `.vscode` folder to
 
The question is, how to modify the file  `task.json`

**Comment by cheveron** [comment]
Closing this because wine is no-longer a dependency:

https://github.com/cheveron/sebasic4/wiki/Developer-guide#Build-SE-Basic-IV-from-source
